### Получить все маркеры карты
GET http://localhost:7254/api/Map/markers
Accept: application/json

### Получить настройки карты по умолчанию
GET http://localhost:7254/api/Map/options/default
Accept: application/json

### Получить образцы для сектора дендрологии
GET http://localhost:7254/api/Specimen/sector/0
Accept: application/json

### Получить образцы для сектора флоры
GET http://localhost:7254/api/Specimen/sector/1
Accept: application/json

### Получить расположение образца (если есть в базе образец с id=1)
GET http://localhost:7254/api/Specimen/1/location
Accept: application/json 